# Generated by Django 4.0.5 on 2022-10-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='subject',
        ),
        migrations.AddField(
            model_name='cluster',
            name='email',
            field=models.CharField(default='hoon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='nodes',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='project_name',
            field=models.CharField(default='project', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='vcpu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
