# Generated by Django 4.0.5 on 2022-10-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EKS', '0002_rename_content_cluster_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='create_date',
        ),
    ]
