# Generated by Django 4.0.5 on 2022-10-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKS', '0004_alter_cluster_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='vcpu',
            new_name='master_cpu',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='ram',
            new_name='master_ram',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='nodes',
            new_name='node_num',
        ),
        migrations.AddField(
            model_name='cluster',
            name='master_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='node_cpu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='node_ram',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
