# Generated by Django 4.0.5 on 2022-10-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKS', '0005_rename_vcpu_cluster_master_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='master_disk',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='node_disk',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
